### ISSUE TITLE
Adding selection column shows ranking column instead

### ISSUE THREAD

**Issue by Reemh** [Caleydo/caleydo_vis_lineup#1]
I tried to add the selection column (mentioned here https://github.com/Caleydo/lineup.js/issues/92) by adding `type: 'selection'` in

``` javascript
    dump: {
          layout: {
            primary: [
              {
                type: 'selection',
                label: 'S'
              },
              {
                type: 'rank',
                width: 40
              },
              col('Name', 220),
              {
                type: 'stacked',
                width: 400,
                children: [col('Structure Add', 100), col('Structure Del', 100), col('Content', 100)]
              },
              col('No Change', 100)
            ]
          }
        }
```

![lineup](https://cloud.githubusercontent.com/assets/7433442/13151952/d00ceb3a-d66c-11e5-86f9-f85d6c01d11c.PNG)

The lineup version from bower_components is "LineUpJS - v0.2.0 - 2016-02-12"
Is there something else I need to update?

**Comment by thinkh** [comment]
Resolved with newer LineUp version.
